version: "3.5"
services: 
    front:
        build: ./front
        container_name: front_blog
        volumes: 
            - ./front:/app
        expose: 
            - 3000
    
    webserver:
        image: nginx
        volumes: 
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./front/build:/usr/share/nginx/html
        ports: 
            - 80:80
            #- 443:433